mixed-port: 7890
allow-lan: false
mode: rule
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
hosts:
  'mtalk.google.com': 108.177.125.188
  'dl.google.com': 180.163.151.161
  'dl.l.google.com': 180.163.151.161

proxies:

#  - name: "Sub"
#    type: trojan
#    server: abc.com
#    port: 443
#    password: XXX
#    skip-cert-verify: false
#    sni: abc.com


proxy-groups:

  - name: "PROXY"
    type: select
    proxies:
      - DIRECT
#      - Sub

  - name: "Blacklist/Whitelist"
    type: select
    proxies:
      - DIRECT
      - PROXY

  - name: "Adblock"
    type: select
    proxies:
      - DIRECT
      - REJECT


rule-providers:

  DirectList:
    type: http
    behavior: classical
    path: ./RuleSet/DirectList.yaml
    url: https://raw.githubusercontent.com/729376442/PublicFiles/main/ClashRules/DirectList.yaml
    interval: 86400

  ProxyList:
    type: http
    behavior: classical
    path: ./RuleSet/ProxyList.yaml
    url: https://raw.githubusercontent.com/729376442/PublicFiles/main/ClashRules/ProxyList.yaml
    interval: 86400

  Adblock:
    type: http
    behavior: classical
    path: ./RuleSet/Adblock.yaml
    url: https://raw.githubusercontent.com/729376442/PublicFiles/main/ClashRules/Adblock.yaml
    interval: 86400

  Unbreak:
    type: http
    behavior: classical
    path: ./RuleSet/Unbreak.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Unbreak.yaml
    interval: 86400

  Advertising:
    type: http
    behavior: classical
    path: ./RuleSet/Advertising.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Guard/Advertising.yaml
    interval: 86400

  Hijacking:
    type: http
    behavior: classical
    path: ./RuleSet/Hijacking.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Guard/Hijacking.yaml
    interval: 86400

  Streaming:
    type: http
    behavior: classical
    path: ./RuleSet/StreamingMedia/Streaming.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/Streaming.yaml
    interval: 86400

  Global:
    type: http
    behavior: classical
    path: ./RuleSet/Global.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Global.yaml
    interval: 86400

  China:
    type: http
    behavior: classical
    path: ./RuleSet/China.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/China.yaml
    interval: 86400

  ChinaIP:
    type: http
    behavior: ipcidr
    path: ./RuleSet/Extra/ChinaIP.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Extra/ChinaIP.yaml
    interval: 86400

rules:

#  - RULE-SET,Adblock,Adblock
  - RULE-SET,Advertising,Adblock
  - RULE-SET,Hijacking,Adblock

  - RULE-SET,DirectList,DIRECT
  - RULE-SET,ProxyList,PROXY

  #神机规则
  - RULE-SET,Unbreak,DIRECT
  - RULE-SET,Streaming,PROXY
  - RULE-SET,Global,PROXY
  - RULE-SET,China,DIRECT
  - RULE-SET,ChinaIP,DIRECT

  #==========================================================
  
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,100.64.0.0/10,DIRECT
  - IP-CIDR,224.0.0.0/4,DIRECT
  - IP-CIDR,fe80::/10,DIRECT
  #- IP-CIDR,119.28.28.28/32,DIRECT
  #- IP-CIDR,182.254.116.0/24,DIRECT
  #- GEOIP,CN,DIRECT
  - MATCH,Blacklist/Whitelist